language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-frontend pismile012/udagram-frontend:latest
  - docker tag udagram-api-feed pismile012/udagram-api-feed:latest
  - docker tag udagram-api-user pismile012/udagram-api-user:latest
  - docker tag reverseproxy pismile012/reverseproxy:latest

after_success:
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pismile012/udagram-api-feed:latest
  - docker push pismile012/udagram-api-user:latest
  - docker push pismile012/udagram-frontend:latest
  - docker push pismile012/reverseproxy:latest